### ISSUE TITLE
Beginner problems from Sweden

### ISSUE THREAD

**Issue by Banditen01** [swedishborgie/weather-station#1]
I really have tried to understand how to make this running but my trial and error just keep on going and going. I realize this is not a support forum but at least I can ask for support

So far I have made it writing to a csv local in same direction as I have placed the files, only changed cflag to -DUSE_CSV=1 and kept the rest as it is and it starts writing to csv, but when I try to configure weather.h/weather.c I'm totally lost.

I really like the thoughts of not wearing out SD card and write directly to a separate media/host but cannot figure out how to do it.

Is there anyway to get some guidance?

**Comment by swedishborgie** [comment]
Currently the application supports output to CSV, a PostgreSQL database, and standard out. All three options can be used to write weather data to another computer / storage volume.

If there's another type of storage you'd like, let me know and it may be possible to add it.

### CSV File
For CSV file storage you can switch the output file in `weather.h` like this:

    #define CSV_FILE "weather.csv"

You also need to change the `Makefile` like this:

    CFLAGS=-DUSE_CSV=1

Just switch the CSV_FILE to a remote volume mount (e.g. cifs, nfs, etc). You could also simply symlink weather.csv to a remote volume or USB drive. Make sure to run `make` after changing weather.h and the Makefile.

### PostgreSQL Database
For a remote PostgreSQL database, just install the database on the remote machine and change the following configuration option in `weather.h`:

    #define PGSQL_CONNECT_STRING "host=remotehost dbname=weather user=weather password=password"

You also need to change the `Makefile` like this:

    CFLAGS=-DUSE_PGSQL=1

Make sure to run `make` after changing weather.h and the Makefile.

### Standard Output

For standard out, from the remote machine use SSH to execute the weather station executable:

    ssh pi-ip-address /path/to/weather > weather.out

This should create a file on your remote machine named weather.out that contains a copy of what was printed to standard out.
